version: '3'
services:
  nginx:
    build: ./requirements/nginx
    image: nginx:latest
    container_name: nginx
    ports:
      -  443:443
    volumes:
      -  wordpress_data:/var/www/wordpress
    restart: always
    networks:
      -  network

  mariadb:
    build: ./requirements/mariadb
    image: mariadb:latest
    container_name: mariadb
    env_file:
      -  .env
    volumes:
      -  mariadb_data:/var/lib/mysql
    restart: always
    networks:
      -  network

  wordpress:
    build: ./requirements/wordpress
    image: wordpress:latest
    container_name: wordpress
    depends_on:
      - mariadb
    restart: always
    env_file:
      -  .env
    volumes:
      -  wordpress_data:/var/www/wordpress
    networks:
      -  network


networks:
  network:
    driver: bridge

volumes:
  wordpress_data:
      driver: local
      driver_opts:
        type: none
        device: /home/alvicina/data/wordpress
        o: bind
  mariadb_data:
      driver: local
      driver_opts:
        type: none
        device: /home/alvicina/data/mysql
        o: bind
